# Generated by Django 3.1.8 on 2021-06-15 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='income',
            name='repetitive_interval',
            field=models.PositiveSmallIntegerField(choices=[(1, 'DAYS'), (2, 'WEEKS'), (3, 'MONTHS'), (4, 'YEARS'), (5, 'N/A')], default=5),
        ),
        migrations.AddField(
            model_name='income',
            name='repetitive_time',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='outcome',
            name='repetitive_interval',
            field=models.PositiveSmallIntegerField(choices=[(1, 'DAYS'), (2, 'WEEKS'), (3, 'MONTHS'), (4, 'YEARS'), (5, 'N/A')], default=5),
        ),
        migrations.AddField(
            model_name='outcome',
            name='repetitive_time',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='balance',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'CURRENT'), (2, 'SAVINGS')]),
        ),
        migrations.AlterField(
            model_name='income',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'SALARY'), (2, 'BONUS'), (3, 'GIFT'), (4, 'OTHER')]),
        ),
        migrations.AlterField(
            model_name='outcome',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'RENT'), (2, 'BILLS'), (3, 'CAR'), (4, 'TRAVEL'), (5, 'HEALTH'), (6, 'GROCERIES'), (7, 'FUN'), (8, 'CLOTHES'), (9, 'CHARITY')]),
        ),
    ]
