# Generated by Django 3.1.8 on 2021-06-15 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0002_auto_20210615_1959'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='balance',
            name='date',
        ),
        migrations.AddField(
            model_name='balance',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='income',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='outcome',
            name='date',
            field=models.DateField(),
        ),
    ]
