# Generated by Django 3.1.8 on 2021-06-15 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0003_auto_20210615_2057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balance',
            name='value',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='income',
            name='value',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='outcome',
            name='value',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
