# Generated by Django 3.1.8 on 2021-06-17 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0004_auto_20210616_0031'),
    ]

    operations = [
        migrations.AddField(
            model_name='income',
            name='comment_char',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='income',
            name='comment_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
