# Generated by Django 3.1.8 on 2021-05-27 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('airpollution', '0002_auto_20210527_1440'),
    ]

    operations = [
        migrations.AddField(
            model_name='pollutantentry',
            name='country',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='airpollution.country'),
            preserve_default=False,
        ),
    ]
