# Generated by Django 3.1.8 on 2021-05-27 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airpollution', '0003_pollutantentry_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='pollutantentry',
            name='year',
            field=models.IntegerField(default=2016),
            preserve_default=False,
        ),
    ]
